"""
Class mixins (not general) for resdepGUI related to fitting curves to the data generated by resdep.

ONLY for use (import) in resdepGUI
"""

from typing import Union, Protocol, TYPE_CHECKING
import logging, traceback
import builtins
import numpy as np
import numpy.typing as npt
from scipy import optimize

from PySide6.QtWidgets import (
    QCheckBox,
    QMessageBox
)

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg

from resdep.experiment import ResonantDepolarisation
from resdep._calculations import energy_calc, freq_calc, model

if TYPE_CHECKING:
    class HasValueProtocol(Protocol):
        @property
        def freqs_array(self) -> npt.NDArray[np.float64]: ...
        @property 
        def checked_sectors(self) -> list[str]: ...
        @checked_sectors.setter
        def checked_sectors(self, value) -> list[str]: ...
        @property
        def sectors(self) -> list[str]: ...
        @sectors.setter
        def sectors(self, value) -> list[str]: ...
        @property
        def ratio_loss(self,) -> dict[str, npt.NDArray[np.float64]]: ...
        @ratio_loss.setter
        def ratio_loss(self, value) -> dict[str, npt.NDArray[np.float64]]: ...
        @property
        def canvas(self) -> FigureCanvasQTAgg: ...
        @canvas.setter
        def canvas(self, value) -> FigureCanvasQTAgg: ...
        @property
        def resdep(self) -> ResonantDepolarisation: ...
        @resdep.setter
        def resdep(self, value) -> ResonantDepolarisation: ...
else:
    class HasValueProtocol: ...


class Mixin(HasValueProtocol):

    def calculate_fitting_mask(self) -> tuple[list[bool], tuple[np.floating], tuple[np.floating]]:
        """
        Grabs the current limits of the interactive plot (including when it is zoomed in) and calculates the frequency range displayed. \\
        This is then used as a mask to fit error functions in fit_error_functions()

        Returns
        -------
        mask: list[bool]
            Binary mask for the frequency range shown in the interactive plot
        xlims: tuple[np.float64]
            Current x-limits (range) of the interactive plot
        ylims: tuple[np.float64]
            Same for y as for x
        """
        xlims = self.canvas.axes.get_xlim() # tuple[lower_bound, upper_bound]
        ylims = self.canvas.axes.get_ylim()
        mask = np.logical_and(self.freqs_array > xlims[0], self.freqs_array < xlims[1])

        return mask, xlims, ylims

    def fit_error_functions(self, mask: Union[list[bool], "builtins.ellipsis"] = ...) -> tuple[dict[str, npt.NDArray[np.floating]], dict[str, float], dict[str, float], str]:
        """
        Fits an error function to the ratio beam loss data. \\
        Does this for every checked sector on the GUI

        Parameters
        ----------
        **kwargs
            Binary mask for the frequency range

        Returns
        -------
        y_model: dict[str, npt.NDArray[np.float64]]
            ydata for the error function model as a dictionary, where each key is a sector
        fitted_beam_energies: dict[str, float]
            beam energies derived from the fit (middle of the inflection point of the error function)
        fit_results: str
            formatted string detailing the resonance frequency, corresponding energy, and goodness-of-fit (r square)
        """

        # fit results dicts
        y_model: dict[str, npt.NDArray[np.float64]] = {}
        fitted_beam_energy_frequencies: dict[str, float] = {}
        fitted_beam_energies: dict[str, float] = {}
        fitted_beam_energy_stddevs: dict[str, float] = {}
        fit_results: str = ""

        for sector in self.checked_sectors:
            try:
                # --- calculate fit
                popt, pcov = optimize.curve_fit(
                    f       = model, 
                    xdata   = self.freqs_array[mask], 
                    ydata   = self.ratio_loss[f"{sector}B"][mask], 
                    p0      = [self.resdep.res_freq, 0.2, 0.04, 1],
                    maxfev  = 8000
                )
                y_model[f"{sector}B"] = model(self.freqs_array[mask], *popt)

                mean_freq       = popt[0]
                mean_energy     = energy_calc(freq=mean_freq, f_rev=self.resdep.f_rev, harmonic=self.resdep.harmonic)
                sigma_freq      = np.sqrt(np.diag(pcov))[0]
                sigma_energy    = (
                    energy_calc(freq=(mean_freq + sigma_freq), f_rev=self.resdep.f_rev, harmonic=self.resdep.harmonic) 
                    - energy_calc(freq=(mean_freq - sigma_freq), f_rev=self.resdep.f_rev, harmonic=self.resdep.harmonic)
                )

                fitted_beam_energy_frequencies[f"{sector}B"] = mean_freq  
                fitted_beam_energies[f"{sector}B"]           = mean_energy
                fitted_beam_energy_stddevs[f"{sector}B"]     = sigma_energy

                # -- calculate goodness of fit
                # residual sum of squares
                ss_res = np.sum((self.ratio_loss[f"{sector}B"][mask] - y_model[f"{sector}B"])**2)
                # total sum of squares
                ss_tot = np.sum((self.ratio_loss[f"{sector}B"][mask] - np.mean(self.ratio_loss[f"{sector}B"][mask]))**2)
                # r-squared
                r2 = 1 - (ss_res / ss_tot)

                fit_results += f"sector={int(sector):02d}, f0={mean_freq:0.3f} kHz, E0={mean_energy:0.5f} GeV, r^2={r2:0.2f}\n"

            except RuntimeError:
                logging.error(traceback.format_exc())
                fit_results += f"sector={sector}, fit failed! (did not converge)\n"

    
        print(f"fitted_beam_energy_stddevs={fitted_beam_energy_stddevs}")

        return y_model, fitted_beam_energies, fitted_beam_energy_stddevs, fit_results
    
    def automagic_fit(self, ) -> None:
        """
        Calculates best guess for resonance in the data (based off derivative cdf -> gauss) \\
        Applies fit over best guess of frequency range.
        """

        # do derivative of fit. Could outsource to _plotting here? Do it in main GUI
        # find argmax
        # find mean of argmax within a certain range (if multiple sectors selected)
        # define frequency range for fit. could be +- 1 KHz, 0.5 KHz?
        # calculate mask using mask = np.logical_and(self.freqs_array > left_boundry, self.freqs_array < right_boundry)
        # call fit_error_functions
        # plot in main GUI
        # verify
        # done :)

        return None
    

if __name__ == "__main__":
    print("_fitting.py contains class mixin functions for resdepGUI.py and should not be run directly.")
