name: ci 
on:
  push:
    branches:
      - kubili-refactor 
permissions:
  contents: write
env:
  SITE_URL: https://liamjwatson.github.io/resdep/
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9.23
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }} 
          path: ~/.cache 
          restore-keys: |
            mkdocs-material-
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
      - run: pip install mkdocs-material==9.7.6
      - run: pip install mkdocs-autorefs==1.4.4
      - run: pip install mkdocstrings-python==1.18.2
      - run: pip install griffe==1.14.0
      - run: mkdocs build --verbose
      - run: mkdocs gh-deploy --force --clean
